version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      # Add deployment steps for sandbox environment
      - deploy:
          name: Deploy to Sandbox
          command: |
            # Add your deployment commands for sandbox environment here
            "echo Deploying to sandbox"
            
      # Add deployment steps for dev environment
      - deploy:
          name: Deploy to Dev
          command: |
            # Add your deployment commands for dev environment here
            "echo Deploying to dev"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
