version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Echo branch name
          command: echo "I am on main"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Echo branch name
          command: echo "I am not on main"


workflows:
  my-workflow:
    jobs:
      - my-job:
          filters:
            branches:
              only: main
